### ISSUE TITLE
Add support for BackgroundTasks

### ISSUE THREAD

**Issue by mvanderlee** [vortico/flama#39]
Add BackgroundTasks via an injectable.

**Comment by perdy** [comment]
The same I told in #37 could be applied here. I don't see a huge gain in making the dependency injection works with BackgroundTasks because those aren't reflected in API schema. I understand it helps with coding under an IDE but as background tasks are called from endpoints and those already have dependency injection it could be done by relaying the dependencies.

My thoughts are the same here, maybe a plugin is the way to go for this kind of enhanced functionality.

**Comment by migduroli** [comment]
@perdy, I also think we should close this PR. I'm afraid the current state of the project is no longer compatible with these changes. Indeed, this might've been resolved indirectly via other changes that have come up over the last few months for the release of v1.0.0. We should consider to close the issue, and PR, and re-consider whether this is still needed in the framework over a discussion prior to any work. This way we can ensure we are note duplicating efforts. And, for sure, thanks a lot to @mvanderlee for this and any future suggestions :)
